name: Continious Delivery

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    types: [published, prereleased]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish-release"
  publish-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Login at Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Build images
      run: |
        docker buildx build . \
          --platform linux/arm,linux/amd64 \
          --tag horizon0156/occu-hmip:latest \
          --tag horizon0156/occu-hmip:${GITHUB_REF##*/} \
          --push
